Update workflows (#341)
Update the workflows to add an additional one for updating the so-info.json file rather than including that as part of every deploy.

diff --git a/.github/workflows/deploy-pages.yml b/.github/workflows/deploy-pages.yml
--- a/.github/workflows/deploy-pages.yml
+++ b/.github/workflows/deploy-pages.yml
@@ -156,12 +156,26 @@ jobs:
             gh release upload mod-mirror --clobber "metadata.json"
           fi
 
-      - name: Update so-info.json
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - name: Trigger so-info.json update if needed
         run: |
-          cd source/scripts
-          npx tsx ./update-so-info.ts
+          if ls ./mod-mirror/* 1> /dev/null 2>&1; then
+            response=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
+              -H "Accept: application/vnd.github.v3+json" \
+              -H "Authorization: token ${{ secrets.METRICS_TOKEN }}" \
+              https://api.github.com/repos/${{ github.repository }}/actions/workflows/update-so-info.yml/dispatches \
+              -d '{"ref":"${{ github.ref }}"}')
+            if [ $response -ne 204 ]; then
+              echo "Workflow dispatch failed with response code $response"
+              exit 1
+            fi
+          fi
+
+      - name: Restore so-info.json cache
+        uses: actions/cache/restore@v4
+        with:
+          path: ./source/website/public/so-info.json
+          key: so-info-
+          restore-keys: so-info-
 
       - name: Process the json (schedule)
         if: (github.event_name == 'schedule' || inputs.recheckUrls == true)
@@ -185,7 +199,6 @@ jobs:
             source/website/public/covers \
             source/website/public/funding-info.json \
             source/website/public/mod-metadata.json \
-            source/website/public/so-info.json
 
       - name: Build website
         run: |
