Revert "Update deployment workflow to conditionally update so-info.json based on mod mirror changes"
This reverts commit 747c046ff59533e1efdc2f0211c3eb5a6d43e623.

diff --git a/.github/workflows/deploy-pages.yml b/.github/workflows/deploy-pages.yml
--- a/.github/workflows/deploy-pages.yml
+++ b/.github/workflows/deploy-pages.yml
@@ -52,8 +52,6 @@ concurrency:
 jobs:
   # Single deploy job since we're just deploying
   deploy:
-    outputs:
-      update-so-info: ${{ steps.update-so-info.outputs.update }}
     environment:
       name: github-pages
       url: ${{ steps.deployment.outputs.page_url }}
@@ -162,13 +160,18 @@ jobs:
             gh release upload "${{ env.MIRROR_METADATA_RELEASE }}" --clobber "metadata.json"
           fi
 
-      - name: Check if so-info.json update needed
-        id: update-so-info
+      - name: Trigger so-info.json update if needed
         run: |
           if ls ./mod-mirror/* 1> /dev/null 2>&1; then
-            echo "update=true" >> $GITHUB_OUTPUT
-          else
-            echo "update=false" >> $GITHUB_OUTPUT
+            response=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
+              -H "Accept: application/vnd.github.v3+json" \
+              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+              https://api.github.com/repos/${{ github.repository }}/actions/workflows/update-so-info.yml/dispatches \
+              -d '{"ref":"${{ github.ref }}"}')
+            if [ $response -ne 204 ]; then
+              echo "Workflow dispatch failed with response code $response"
+              exit 1
+            fi
           fi
 
       - name: Restore so-info.json cache
@@ -230,7 +233,3 @@ jobs:
       - name: Deploy to GitHub Pages
         id: deployment
         uses: actions/deploy-pages@v4
-  update-so-info:
-    needs: deploy
-    if: needs.deploy.outputs.update-so-info == 'true'
-    uses: ./.github/workflows/update-so-info.yml
