Update workflows (#350)
Run PR check when created by the GitHub bot

diff --git a/.github/workflows/import-mods.yml b/.github/workflows/import-mods.yml
--- a/.github/workflows/import-mods.yml
+++ b/.github/workflows/import-mods.yml
@@ -44,6 +44,7 @@ on:
 permissions:
   contents: write
   pull-requests: write
+  actions: write
 
 jobs:
   # Single deploy job since we're just deploying
@@ -116,11 +117,25 @@ jobs:
 
       - name: Create PR
         if: (inputs.createPr == true)
+        id: create-pr
         uses: peter-evans/create-pull-request@v6
         with:
           title: ${{ fromJson(env.COMMIT_SUBJECT) }}
           body: ${{ fromJson(env.COMMIT_BODY) }}
           branch: import/${{ env.BRANCH_NAME }}
+
+      - name: Trigger checks
+        if: (inputs.createPr == true)
+        run: |
+          response=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
+            -H "Accept: application/vnd.github.v3+json" \
+            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+            ${{ github.api_url }}/repos/${{ github.repository }}/actions/workflows/pr.yml/dispatches \
+            -d '{ "ref": "${{ github.ref }}", "inputs": { "pr_number": "${{ steps.create-pr.outputs.pull-request-number }}" }')
+          if [ $response -ne 204 ]; then
+            echo "Workflow dispatch failed with response code $response"
+            exit 1
+          fi
 
       - name: Push the updated files
         if: ((inputs.createPr != true) && (env.MODS_UPDATED == 'yes'))
